# Generated by Django 4.1.2 on 2022-10-09 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firtsname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("telephone", models.CharField(max_length=15)),
                ("company", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("dateofbirht", models.DateField()),
                ("jobrol", models.CharField(max_length=40)),
                ("createdate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Donation_Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal", models.IntegerField()),
                ("description", models.CharField(max_length=500)),
                ("startdate", models.DateField()),
                ("enddate", models.DateField()),
                ("active", models.BooleanField()),
                ("createdate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobrol", models.CharField(max_length=40)),
                ("createdate", models.DateTimeField(auto_now_add=True)),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.donation"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="donation",
            name="donation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.donation_goal"
            ),
        ),
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobrol", models.CharField(max_length=40)),
                ("createdate", models.DateTimeField(auto_now_add=True)),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.donation"
                    ),
                ),
            ],
        ),
    ]
