# Generated by Django 4.1.2 on 2022-10-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_donation_donation_goal_job_donation_donation_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Job",),
    ]
