# Generated by Django 4.1.2 on 2022-10-09 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_delete_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobgroup", models.CharField(max_length=40)),
                ("createdate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobrol", models.CharField(max_length=40)),
                ("createdate", models.DateTimeField(auto_now_add=True)),
                (
                    "jobgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.jobgroup"
                    ),
                ),
            ],
        ),
    ]
