# Generated by Django 4.1.2 on 2022-10-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_jobgroup_job"),
    ]

    operations = [
        migrations.DeleteModel(name="Collaboration",),
    ]
