# Generated by Django 4.1.2 on 2022-10-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_collaboration"),
    ]

    operations = [
        migrations.RemoveField(model_name="donation", name="donation",),
        migrations.DeleteModel(name="Collaboration",),
        migrations.DeleteModel(name="Donation",),
    ]
