# Generated by Django 4.1.2 on 2022-10-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_donation_donation_delete_collaboration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firtsname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("telephone", models.CharField(max_length=15)),
                ("company", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("dateofbirht", models.DateField()),
                ("createdate", models.DateTimeField(auto_now_add=True)),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.donation_goal",
                    ),
                ),
                (
                    "jobrol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.job"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdate", models.DateTimeField(auto_now_add=True)),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.donation"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.job"
                    ),
                ),
            ],
        ),
    ]
