# Generated by Django 4.1.2 on 2022-10-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_donation_collaboration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation_goal", options={"verbose_name_plural": "Donations Goal"},
        ),
        migrations.RenameField(
            model_name="donation", old_name="donation", new_name="Donation_Goal",
        ),
    ]
