# Generated by Django 4.1.2 on 2022-10-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_donation_goal_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="donation", name="Donation_Goal",),
        migrations.RemoveField(model_name="donation", name="jobrol",),
        migrations.RemoveField(model_name="job", name="jobgroup",),
        migrations.DeleteModel(name="Collaboration",),
        migrations.DeleteModel(name="Donation",),
        migrations.DeleteModel(name="Donation_Goal",),
        migrations.DeleteModel(name="Job",),
        migrations.DeleteModel(name="JobGroup",),
    ]
