# Generated by Django 4.1.2 on 2022-10-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_contact_embrace"),
    ]

    operations = [
        migrations.DeleteModel(name="Contact",),
    ]
