# Generated by Django 4.1.2 on 2022-10-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_contact_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact", name="message", field=models.TextField(),
        ),
    ]
