# Generated by Django 4.1.1 on 2022-10-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_usercolaborator_alter_embrace_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostUserColaborator',
        ),
        migrations.DeleteModel(
            name='UserColaborator',
        ),
    ]
