# Generated by Django 4.1.1 on 2022-10-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_usercolaborator_postusercolaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercolaborator',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
