# Generated by Django 4.1.1 on 2022-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_usercolaborator_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='postusercolaborator',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
