# Generated by Django 4.1.1 on 2022-10-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_postusercolaborator_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercolaborator',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='usercolaborator',
            name='suscripcion',
        ),
        migrations.DeleteModel(
            name='PostUserColaborator',
        ),
        migrations.DeleteModel(
            name='UserColaborator',
        ),
    ]
