# Generated by Django 4.1.1 on 2022-10-30 16:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0026_remove_usercolaborator_perfil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserColaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('username', models.CharField(max_length=70)),
                ('pwd', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, upload_to='avatar')),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.perfil')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.suscripcion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User colaborators',
            },
        ),
        migrations.CreateModel(
            name='PostUserColaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.usercolaborator')),
            ],
            options={
                'verbose_name_plural': 'User Post colaborators',
            },
        ),
    ]
