# Generated by Django 4.1.1 on 2022-10-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_usercolaborator_postusercolaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercolaborator',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
