# Generated by Django 4.1.1 on 2022-11-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_postusercolaborator_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Author [ Autor ]'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category [ Categoria ]'},
        ),
        migrations.AlterModelOptions(
            name='collaboration',
            options={'verbose_name_plural': 'Collaboration [ Colaboracion ]'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact [ Contactanos ]'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name_plural': 'Donation [ Donacion ]'},
        ),
        migrations.AlterModelOptions(
            name='donation_goal',
            options={'verbose_name_plural': 'Donation_Goal [ Meta ]'},
        ),
        migrations.AlterModelOptions(
            name='embrace',
            options={'verbose_name_plural': 'Embrace [ Adoptar ]'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'Job [ Trabajo ]'},
        ),
        migrations.AlterModelOptions(
            name='jobgroup',
            options={'verbose_name_plural': 'JobGroup [ Grupo de trabajo ]'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfil [ Perfil ]'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post [ Publicación ]'},
        ),
        migrations.AlterModelOptions(
            name='postusercolaborator',
            options={'verbose_name_plural': 'PostUserColaborator [Publicación:User:Colaborador]'},
        ),
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'verbose_name_plural': 'Subscription [ Suscripción ]'},
        ),
        migrations.AlterModelOptions(
            name='usercolaborator',
            options={'verbose_name_plural': 'UserColaborator [User:Colaborador]'},
        ),
        migrations.AddField(
            model_name='usercolaborator',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='usercolaborator',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición'),
        ),
    ]
