# Generated by Django 4.1.1 on 2022-11-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Author [ Autor ]'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Category [ Categoria ]'},
        ),
        migrations.AlterModelOptions(
            name='collaboration',
            options={'verbose_name': 'Colaboracion', 'verbose_name_plural': 'Collaboration [ Colaboracion ]'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contáctanos', 'verbose_name_plural': 'Contact [ Contáctanos ]'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Donacion', 'verbose_name_plural': 'Donation [ Donacion ]'},
        ),
        migrations.AlterModelOptions(
            name='donation_goal',
            options={'verbose_name': 'Meta:Donacion', 'verbose_name_plural': 'Donation_Goal [ Meta:Donacion ]'},
        ),
        migrations.AlterModelOptions(
            name='embrace',
            options={'verbose_name': 'Adoptar', 'verbose_name_plural': 'Embrace [ Adoptar ]'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Trabajo', 'verbose_name_plural': 'Job [ Trabajo ]'},
        ),
        migrations.AlterModelOptions(
            name='jobgroup',
            options={'verbose_name': 'Grupo de trabajo', 'verbose_name_plural': 'JobGroup [ Grupo de trabajo ]'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfil [ Perfil ]'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Publicación', 'verbose_name_plural': 'Post [ Publicación ]'},
        ),
        migrations.AlterModelOptions(
            name='postusercolaborator',
            options={'verbose_name': 'Publicación:User:Colaborador', 'verbose_name_plural': 'PostUserColaborator [Publicación:User:Colaborador]'},
        ),
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'verbose_name': 'Suscripción', 'verbose_name_plural': 'Subscription [ Suscripción ]'},
        ),
        migrations.AlterModelOptions(
            name='usercolaborator',
            options={'verbose_name': 'User:Colaborador', 'verbose_name_plural': 'UserColaborator [User:Colaborador]'},
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición'),
        ),
        migrations.AddField(
            model_name='postusercolaborator',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='postusercolaborator',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición'),
        ),
    ]
