# Generated by Django 4.1.1 on 2022-11-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name_plural': 'Message [ Mensaje ]'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': 'Room [ User:Room ]'},
        ),
    ]
