# Generated by Django 4.1.1 on 2022-11-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': ' Mensaje', 'verbose_name_plural': 'Message [ Mensaje ]'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': ' User:Room', 'verbose_name_plural': 'Room [ User:Room ]'},
        ),
    ]
